package com.airkuapp.ui.theme

import androidx.compose.ui.graphics.Color

// --- Dark Mode Palette ---
val DarkSurface = Color(0xFF000000)
val DarkSurfaceDim = Color(0xFF000000)
val DarkSurfaceBright = Color(0xFF1A1A1A)
val DarkSurfaceContainerLowest = Color(0xFF0E0E0E)
val DarkSurfaceContainerLow = Color(0xFF141414)
val DarkSurfaceContainer = Color(0xFF1A1A1A)
val DarkSurfaceContainerHigh = Color(0xFF202020)
val DarkSurfaceContainerHighest = Color(0xFF2A2A2A)
val DarkOnSurface = Color(0xFFE5E2E1)
val DarkOnSurfaceVariant = Color(0xFFBBCABC)
val DarkInverseSurface = Color(0xFFE5E2E1)
val DarkInverseOnSurface = Color(0xFF313030)
val DarkOutline = Color(0xFF869488)
val DarkOutlineVariant = Color(0xFF3C4A3F)
val DarkSurfaceTint = Color.Transparent
val DarkPrimary = Color(0xFF53E894)
val DarkOnPrimary = Color(0xFF00391D)
val DarkPrimaryContainer = Color(0xFF2CCB7B)
val DarkOnPrimaryContainer = Color(0xFF00502B)
val DarkInversePrimary = Color(0xFF006D3D)
val DarkSecondary = Color(0xFFADC6FF)
val DarkOnSecondary = Color(0xFF002E6A)
val DarkSecondaryContainer = Color(0xFF0566D9)
val DarkOnSecondaryContainer = Color(0xFFE6ECFF)
val DarkTertiary = Color(0xFFFFC379)
val DarkOnTertiary = Color(0xFF472A00)
val DarkTertiaryContainer = Color(0xFFF79F0E)
val DarkOnTertiaryContainer = Color(0xFF623C00)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF000000)
val DarkOnBackground = Color(0xFFE5E2E1)
val DarkSurfaceVariant = Color(0xFF1A1A1A)

// --- Light Mode Palette ---
val LightSurface = Color(0xFFF8F9FA)
val LightSurfaceDim = Color(0xFFD9DADB)
val LightSurfaceBright = Color(0xFFF8F9FA)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF3F4F5)
val LightSurfaceContainer = Color(0xFFEDEEEF)
val LightSurfaceContainerHigh = Color(0xFFE7E8E9)
val LightSurfaceContainerHighest = Color(0xFFE1E3E4)
val LightOnSurface = Color(0xFF191C1D)
val LightOnSurfaceVariant = Color(0xFF3C4A3F)
val LightInverseSurface = Color(0xFF2E3132)
val LightInverseOnSurface = Color(0xFFF0F1F2)
val LightOutline = Color(0xFF6C7B6E)
val LightOutlineVariant = Color(0xFFBBCABC)
val LightSurfaceTint = Color(0xFF006D3D)
val LightPrimary = Color(0xFF006D3D)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF2CCB7B)
val LightOnPrimaryContainer = Color(0xFF00502B)
val LightInversePrimary = Color(0xFF49E08D)
val LightSecondary = Color(0xFF575E70)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD9DFF5)
val LightOnSecondaryContainer = Color(0xFF5C6274)
val LightTertiary = Color(0xFF585F6C)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFACB3C2)
val LightOnTertiaryContainer = Color(0xFF3E4552)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF93000A)
val LightBackground = Color(0xFFF8F9FA)
val LightOnBackground = Color(0xFF191C1D)
val LightSurfaceVariant = Color(0xFFE1E3E4)

